### ISSUE TITLE
Update JavaScript Code to Adhere to Modern Guidelines

### ISSUE THREAD

**Issue by AlejandroBlanco2001** [farhan7reza7/diff-ymd-package#52]
#### Feature_Request:

Update JavaScript Code to Adhere to Modern Guidelines

**Feature Description**

Upon reviewing the package's source code, it has come to our attention that there are still some occurrences of var declarations.

**Reason for the Feature**

While this feature may not directly impact performance, it aligns the codebase with modern JavaScript guidelines and styling.

**Additional Information**

N/A

**Comment by farhan7reza7** [comment]
yeah sure, we will update to follow es6 and beyond after considering consistency across browsers, however for as long as we think right now consistent, we will fix for `var`, thank you!

**Comment by AlejandroBlanco2001** [comment]
Thanks @farhan7reza7, looking for help with the docs and the codebase

**Comment by farhan7reza7** [comment]
ok, let me know your repos urls, i will see how can i help for docs and the codebase, thank you!

**Comment by farhan7reza7** [comment]
> Author
ok, let me know your repos urls, i will see how can i help for docs and the codebase, thank you!

**Comment by AlejandroBlanco2001** [comment]
I mean to help this repo :smile: , my bad haha

**Comment by farhan7reza7** [comment]
> I mean to help this repo 😄 , my bad haha

okay, it's my bad to interpret, sorry, okay we will consider your help  for docs and the codebase, even if you yourself make required changes and make pull request or can helps with raising required issues, or when we will make wide ranged changes in the codebase and docs, we will raise issue and consider assigning you something there; keep connected and increase the discoverability of this repo even by starring this, because more the stars, better the discoverability  of a repo as per github searching algo, hoping for your helps for the better and standard way of our contributions to the open source community. thank you!
